### PR TITLE
FIX: Chart.js v3.5 not including helpers in main Chart object.

### PR DESCRIPTION
**Pull request by MantasS0**
https://www.chartjs.org/docs/3.5.0/getting-started/integration.html#helper-functions

### CODE REVIEW

**Comment by MantasS0** [comment]
Great package. I tried to fix the issue I stated above, ran all that was defined in read me and contributing. Seems all good, but I would appreciate if you could take a second look, fix anything that I missed and update this package. :)

**Comment by alexkuc** [comment]
Hi! Thank you so much for taking the time to update this package. For some reason, I didn't receive any notification for this PR and noticed just now. I will review this in the coming days.

**Comment by alexkuc** [comment]
It's great PR! Some clarification @MantasS0  before I do merge:

| commit | status |
| :--- | :---: |
| 2ba045a4df310dd35272e83bb8975a7aaa1f4099 | cherry-picked |
| 2ba045a4df310dd35272e83bb8975a7aaa1f4099 | cherry-picked |
| 9f072479f073ceebe5fa0125e7720c5765e476c0 | cherry-picked |
| 6b399d0dbd4a2414bd45ea219335737aeaa1528b | is this needed? I feel that this addresses something different? |
| a69ab316ffe367f54ddbadfabbd5cffe7f9d5815 | is this needed? I feel that this addresses something different? |
| 7f525e952c98636c6a217225d11afcd2e7f982ce | new commit by new (removed `helpers` var from `utils.js`) |

**Comment by alexkuc** [comment]
Superseded by #4

**Pull request closed without merging**
